### ISSUE TITLE
input  和 textarea 中的文字选中时不应该被触发

### ISSUE THREAD

**Issue by naoyeye** [oyrx/word_frequency#4]
否则就会变成这样：

![image](https://user-images.githubusercontent.com/434428/43948877-a171f034-9cbe-11e8-804f-5135b12bd8ce.png)

**Comment by oyrx** [comment]
Fixed at [INPUT & TEXTAREA fix.](https://github.com/oyrx/word_frequency/commit/1a424b8e031f3b880e3cacc0b30004fac22c0eb1).
